export const mountains = [
  // ======================
  // 🌍 8000m Peaks (14)
  // ======================
  {
    name: 'Everest',
    latitude: 27.9881,
    longitude: 86.925,
    altitude: 8848,
    region: 'Himalayas',
    country: 'Nepal/China',
    description: 'Highest mountain in the world (8,848m).',
  },
  {
    name: 'K2',
    latitude: 35.8808,
    longitude: 76.5155,
    altitude: 8611,
    region: 'Karakoram',
    country: 'Pakistan/China',
    description: 'Second highest and most dangerous mountain.',
  },
  {
    name: 'Kangchenjunga',
    latitude: 27.7025,
    longitude: 88.1475,
    altitude: 8586,
    region: 'Himalayas',
    country: 'Nepal/India',
    description: 'Third highest peak in the world.',
  },
  {
    name: 'Lhotse',
    latitude: 27.9617,
    longitude: 86.933,
    altitude: 8516,
    region: 'Himalayas',
    country: 'Nepal',
    description: 'Connected to Everest via South Col.',
  },
  {
    name: 'Makalu',
    latitude: 27.8897,
    longitude: 87.0883,
    altitude: 8485,
    region: 'Himalayas',
    country: 'Nepal/China',
    description: 'Fifth highest mountain in the world.',
  },
  {
    name: 'Cho Oyu',
    latitude: 28.0942,
    longitude: 86.6608,
    altitude: 8188,
    region: 'Himalayas',
    country: 'Nepal/China',
    description: 'One of the easiest 8000m peaks.',
  },
  {
    name: 'Dhaulagiri I',
    latitude: 28.6966,
    longitude: 83.487,
    altitude: 8167,
    region: 'Himalayas',
    country: 'Nepal',
    description: 'Seventh highest peak in the world.',
  },
  {
    name: 'Manaslu',
    latitude: 28.5497,
    longitude: 84.5597,
    altitude: 8163,
    region: 'Himalayas',
    country: 'Nepal',
    description: 'Mountain of the Spirit.',
  },
  {
    name: 'Nanga Parbat',
    latitude: 35.2372,
    longitude: 74.5892,
    altitude: 8126,
    region: 'Himalayas',
    country: 'Pakistan',
    description: 'Killer Mountain due to high fatality rate.',
  },
  {
    name: 'Annapurna I',
    latitude: 28.5961,
    longitude: 83.8203,
    altitude: 8091,
    region: 'Himalayas',
    country: 'Nepal',
    description: 'One of the most dangerous mountains.',
  },
  {
    name: 'Gasherbrum I',
    latitude: 35.7245,
    longitude: 76.6965,
    altitude: 8080,
    region: 'Karakoram',
    country: 'Pakistan/China',
    description: 'Hidden Peak.',
  },
  {
    name: 'Broad Peak',
    latitude: 35.8122,
    longitude: 76.5651,
    altitude: 8051,
    region: 'Karakoram',
    country: 'Pakistan/China',
    description: 'Near K2.',
  },
  {
    name: 'Gasherbrum II',
    latitude: 35.7583,
    longitude: 76.6533,
    altitude: 8035,
    region: 'Karakoram',
    country: 'Pakistan/China',
    description: 'More accessible 8000m peak.',
  },
  {
    name: 'Shishapangma',
    latitude: 28.3525,
    longitude: 85.7792,
    altitude: 8027,
    region: 'Tibet',
    country: 'China',
    description: 'Lowest 8000m peak.',
  },

  // ======================
  // 🏔️ Major 7000m Peaks
  // ======================
  {
    name: 'Noshaq',
    latitude: 36.434,
    longitude: 71.823,
    altitude: 7492,
    region: 'Hindu Kush',
    country: 'Afghanistan',
    description: 'Highest mountain in Afghanistan.',
  },
  {
    name: 'Tirich Mir',
    latitude: 36.255,
    longitude: 71.841,
    altitude: 7708,
    region: 'Hindu Kush',
    country: 'Pakistan',
    description: 'Highest peak of Hindu Kush.',
  },
  {
    name: 'Trivor',
    latitude: 36.086,
    longitude: 75.175,
    altitude: 7720,
    region: 'Karakoram',
    country: 'Pakistan',
    description: 'Remote Karakoram peak.',
  },

  // ======================
  // 🇮🇷 Iranian Peaks
  // ======================
  {
    name: 'Damavand',
    latitude: 35.951,
    longitude: 52.109,
    altitude: 5610,
    region: 'Alborz',
    country: 'Iran',
    description: 'Highest mountain in Iran and Middle East.',
  },
  {
    name: 'Sabalan',
    latitude: 38.272,
    longitude: 47.845,
    altitude: 4811,
    region: 'Iran',
    country: 'Iran',
    description: 'Dormant volcano in northwest Iran.',
  },
  {
    name: 'Alam Kuh',
    latitude: 36.384,
    longitude: 50.983,
    altitude: 4850,
    region: 'Alborz',
    country: 'Iran',
    description: 'Technical climbing peak in Iran.',
  },
];
